<a href="https://colab.research.google.com/github/badriadhikari/2019-Spring-DL/blob/master/Test/Sample_Questions_on_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

QUESTION. Complete the code below to split the data (768 rows) into training set (XTRAIN and TRAIN) containing the first 700 rows and validation set (XVALIDATION and YVALIDATION) containing the remaining 68 rows

In [2]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
np.random.seed(7)

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)
print(dataset[0:5, :])

XTRAIN = 
YTRAIN = 
XVALIDATION = 
YVALIDATION = 

(768, 9)
[[6.00 148.00 72.00 35.00 0.00 33.60 0.63 50.00 1.00]
 [1.00 85.00 66.00 29.00 0.00 26.60 0.35 31.00 0.00]
 [8.00 183.00 64.00 0.00 0.00 23.30 0.67 32.00 1.00]
 [1.00 89.00 66.00 23.00 94.00 28.10 0.17 21.00 0.00]
 [0.00 137.00 40.00 35.00 168.00 43.10 2.29 33.00 1.00]]


QUESTION. In the code block below, the output of the first two print statements are already there. What will be the output of the last two print statements?

In [7]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
np.random.seed(7)

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)
print(dataset[0:5, :])

XTRAIN = dataset[200:,0:8]
YTRAIN = dataset[200:,8]
XVALIDATION = dataset[:200,0:8]
YVALIDATION = dataset[:200:,8]

print(XVALIDATION.shape)
print(YVALIDATION.shape)

(768, 9)
[[6.00 148.00 72.00 35.00 0.00 33.60 0.63 50.00 1.00]
 [1.00 85.00 66.00 29.00 0.00 26.60 0.35 31.00 0.00]
 [8.00 183.00 64.00 0.00 0.00 23.30 0.67 32.00 1.00]
 [1.00 89.00 66.00 23.00 94.00 28.10 0.17 21.00 0.00]
 [0.00 137.00 40.00 35.00 168.00 43.10 2.29 33.00 1.00]]


QUESTION. The following code throws "Error when checking input: expected to have shape (8,) but got array with shape (5,)" because there is something wrong at line number 19. What do you fix at that line so that this code runs?

In [14]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
np.random.seed(7)

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)

XTRAIN = dataset[200:,0:5]
YTRAIN = dataset[200:,8]
XVALIDATION = dataset[:200,0:5]
YVALIDATION = dataset[:200:,8]

model = Sequential()
model.add(Dense(12, input_dim = 8, activation='sigmoid'))
model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(XTRAIN, YTRAIN, epochs=15, batch_size=10)

(768, 9)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 12)                72        
_________________________________________________________________
dense_20 (Dense)             (None, 8)                 104       
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 9         
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________
None


QUESTION. Complete the code below to have 12 neurons with sigmoid activation in the first layer, 8 neurons in the second layer with sigmoid activation, and 1 neuron in the last layer with sigmoid activation.

In [18]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)

XTRAIN = dataset[200:,0:8]
YTRAIN = dataset[200:,8]
XVALIDATION = dataset[:200,0:5]
YVALIDATION = dataset[:200:,8]

model = Sequential()
model.add(Dense(12, input_dim = 8, activation='sigmoid'))
model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))


(768, 9)


QUESTION. Complete the code below for model.compile() and model.fit(). Choose reasonable parameters for epochs, batch_size, metrics, optimizer and loss.

In [21]:
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

np.set_printoptions(formatter={'float': lambda x: "{0:0.2f}".format(x)})

# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)

XTRAIN = dataset[200:,0:8]
YTRAIN = dataset[200:,8]
XVALIDATION = dataset[:200,0:5]
YVALIDATION = dataset[:200:,8]

model = Sequential()
model.add(Dense(12, input_dim = 8, activation='sigmoid'))
model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

model.compile(                                                           )

model.fit(                                                               )


(768, 9)


QUESTION. Assume that the variable "YVALIDATION" has the true labels (1s and 0s) for the Pima Indians Diabetes Dataset and "prediction" variable contains the predictions from a trained neural network model. Given the following code, calculate the precision, accuracy, and recall.

In [48]:
print(YVALIDATION[0:10])

prediction = model.predict(XVALIDATION)
print('')
print(prediction[0:10])
print ('')
print(prediction[0:10].round())

accuracy = accuracy_score(YVALIDATION[0:10], prediction[0:10].round())
precision = precision_score(YVALIDATION[0:10], prediction[0:10].round())
recall = recall_score(YVALIDATION[0:10], prediction[0:10].round())

print("Accuracy: %.2f%%" % (accuracy * 100.0))
print("Precision: %.2f%%" % (precision * 100.0))
print("Recall: %.2f%%" % (recall * 100.0))

[1.00 0.00 1.00 0.00 1.00 0.00 1.00 0.00 1.00 1.00]

[[0.70]
 [0.17]
 [0.70]
 [0.13]
 [0.62]
 [0.23]
 [0.18]
 [0.35]
 [0.62]
 [0.38]]

[[1.00]
 [0.00]
 [1.00]
 [0.00]
 [1.00]
 [0.00]
 [0.00]
 [0.00]
 [1.00]
 [0.00]]


QUESTION. We are desiging a Neural Network model in Keras for predicting actual values of age on a dataset, i.e. this is a regression problem. Complete the model.compile() function below with an appropriate parameteres for loss, optimizer, and metrics.

In [0]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='sigmoid'))
model.add(Dense(8, activation='sigmoid'))
model.add(Dense(1, activation='linear'))

model.compile(                                     ) 

QUESTION. Of the two models (model1 and model2) below, which is for regression and which is for binary classification? Explain.

In [0]:
model1 = Sequential()
model1.add(Dense(12, input_dim=8, activation='relu'))
model1.add(Dense(8, activation='sigmoid'))
model1.add(Dense(1, activation='linear'))

model2 = Sequential()
model2.add(Dense(12, input_dim=8, activation='sigmoid'))
model2.add(Dense(8, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))
